<div id="main" role="main">
	<section id="s_loader" >
		<img src="img/loader/ajax-loader.gif" />
	</section>
	<section id="s_home" style="display:none">
		<img width="1024" height="619" src="img/slides/f1.jpg" />
	</section>
	<section id="s_learn" style="display:none">
		<h1>Learn</h1>
		<p>ABOUT NICK + CAMPBELL</p>
		<p>After 10 years – a rarity – in the cutthroat world of modeling, Nicholas Lemons finds himself in the enviable position of being one of the most sought after faces in the industry. As the face of numerous luxury fashion brands around the globe. Nicholas has spent years being fit by mastor tailors and thus has developed an innate sense of how garments should fit, feel and look on the body. With Nick + Campbell, Nicholas now brings forth his vision for the every foundation of a well-dressed gentleman’s wardrobe: his underwear.  Using natural fibers such as cotton and sustainable bamboo, Nick + Campbell offers four distinct cuts that move with the body and offer the utmost degree of comfort.</p>
	</section>
</div>