<div id="main" role="main">
	<div id="s_loader" >
		<img src="img/loader/ajax-loader.gif" />
	</div>
	
	
	<section id="s_home" style="display:none">
		<img width="1024" height="619" src="img/slides/f1.jpg" />
	</section>
	
	
	<section id="s_learn" style="display:none">
		<div class="sidebar">
			<h1>Learn</h1>
			<img src="img/learn/crest.png" alt="Nick and Campbell Crest" />
		</div>
		<div style="display:none;" class="section-content">
			<h2>ABOUT NICK + CAMPBELL</h2>
			<p>After 10 years – a rarity – in the cutthroat world of modeling, Nicholas Lemons finds himself in the enviable position of being one of the most sought after faces in the industry. As the face of numerous luxury fashion brands around the globe. Nicholas has spent years being fit by mastor tailors and thus has developed an innate sense of how garments should fit, feel and look on the body. With Nick + Campbell, Nicholas now brings forth his vision for the every foundation of a well-dressed gentleman’s wardrobe: his underwear.  Using natural fibers such as cotton and sustainable bamboo, Nick + Campbell offers four distinct cuts that move with the body and offer the utmost degree of comfort.</p>
			<img class="right" src="img/learn/nick.jpg" alt="Nicholas Lemons" />
			<div class="clearfix"></div>
		</div>
	</section>
	<section id="s_shop" style="display:none">
		<div class="sidebar">
			<h1>Shop</h1>
			<div id="shop_sidenav">
				<h2><a href="#" title="Mens Underwear">Mens Underwear</a></h2>
				<ul>
					<li><a href="#" title="Original Boxer Brief">Original Boxer Brief</a></li>
					<li><a href="#" title="Sexy Campbell Brief">Sexy Campbell Brief</a></li>
				</ul>
			</div>
			<h3>Womens Collection <br/> Coming Soon</h3>
			<img src="img/learn/crest.png" alt="Nick and Campbell Crest" />
		</div>
		<div style="display:none;" class="section-content">	
			<div id="shop_grid">
				<div class="product">
					<a href="#" title="Click to View"><img src="img/shop/products/product-1.png" /></a>
					<a href="#" title="Click to View">Classic Boxer Brief</a>
					<a href="#" title="Click to View">$19.95</a>
				</div>
			</div>
			<img class="right" src="img/shop/shop-side.jpg" alt="Nick and Campbell Mens Underwear">
			<div class="clearfix"></div>
		</div>
	</section>
	
	<section id="s_campaign" style="display:none">
		<div id="lookbook_container" style="width: <?= $this->campaignDivWidth; ?>px;">
			<?php for($i=1;$i<=$this->totalLookbookPages ;$i++): ?>
			<img src="img/lookbook/<?= $i; ?>.jpg" alt="Nick and Campbell Lookbook Page <?= $i; ?>" />
			<?php endfor; ?>
			<div class="clearfix"></div>
		</div>	
		<div id="prev_arrow" class="arrow"></div>
		<div id="next_arrow" class="arrow"></div>
	</section>
	
	
	<section id="s_contact" style="display:none">
		<div class="sidebar">
			<h1>Contact</h1>
			<img src="img/learn/crest.png" alt="Nick and Campbell Crest" />
		</div>
		<div class="section-content">
			<h2>Contact Us Today</h2>
			<h4>info@nickandcampbell.com</h4>	
			<h4>office.917.328.6408</h4>	
			<h4>inquiries welcome</h4>	
			<?= $this->contactForm; ?>
			<div class="clearfix"></div>
		</div>
	</section>
	<div id='overlay'></div>
</div>