<div id="main" role="main">
	<div id="s_loader" >
		<img src="img/loader/ajax-loader.gif" />
	</div>
	
	
	<section id="s_home">
		<img width="1024" height="619" src="img/slides/f1.jpg" />
	</section>
	
	
	<section id="s_learn">
		<div class="sidebar">
			<h1>Learn</h1>
		</div>
		<div style="display:none;" class="section-content">
			<h2>ABOUT NICK + CAMPBELL</h2>
			<p>After 10 years – a rarity – in the cutthroat world of modeling, Nicholas Lemons finds himself in the enviable position of being one of the most sought after faces in the industry. As the face of numerous luxury fashion brands around the globe. Nicholas has spent years being fit by mastor tailors and thus has developed an innate sense of how garments should fit, feel and look on the body. With Nick + Campbell, Nicholas now brings forth his vision for the every foundation of a well-dressed gentleman’s wardrobe: his underwear.  Using natural fibers such as cotton and sustainable bamboo, Nick + Campbell offers five distinct cuts that move with the body and offer the utmost degree of comfort.</p>
			<img class="right" src="img/learn/nick.jpg" alt="Nicholas Lemons" />
			<div class="clearfix"></div>
		</div>
	</section>
	
	
	<section id="s_shop">
		<div class="sidebar">
			<h1>Shop</h1>
			<div id="shop_sidenav">
				<h2><a rel="address:/shop" href="shop" title="Mens Underwear">Mens Underwear</a></h2>
				<ul>
					<?php foreach($this->products as $p): ?>
					<li><a id="sidenav_<?= $p->pretty; ?>" href="<?= $p->href; ?>" rel="address:/<?= $p->href; ?>" title="<?= $p->name; ?>"><?= $p->name; ?></a></li>
					<?php endforeach;?>
				</ul>
			</div>
			<h3>Womens Collection <br/> Coming Soon</h3>
		</div>
			<div style="display:none;" class="section-content">
				<div class="section-content-wrapper">
					<div id="shop_grid">
						<ul class="shop-subnav subnav-grad">
						<li>View</li>
						<li><a href="#" title="View All Items">ALL</a></li>
						</ul>
						<?php foreach($this->products as $p): ?>
						<div class="product">
							<a href="<?= $p->href; ?>" rel="address:/<?= $p->href; ?>" title="Click to View"><img src="img/shop/<?= $p->gender; ?>/<?= $p->category; ?>/thumbs/style-<?= $p->sid; ?>.png" /></a>
							<a href="<?= $p->href; ?>" rel="address:/<?= $p->href; ?>" title="Click to View"><?= $p->name; ?></a>
							<a href="<?= $p->href; ?>" rel="address:/<?= $p->href; ?>" title="Click to View">$<?= $p->price; ?></a>
						</div>
						<?php endforeach; ?>
						<img class="right-img" src="img/shop/shop-side.jpg" alt="Nick and Campbell Mens Underwear">
					</div>
					
					<div id="product_detail"><img class="product-loader" src="img/loader/ajax-loader-bg999.gif" /></div>
				</div>	
			</div>
		
	</section>
	
	
	<section id="s_campaign" class="section">
	<div id="lookbook_wrapper">
		<div id="lookbook_container" style="width: <?= $this->campaignWidth; ?>px;">
			<?php for($i=1;$i<=$this->lookbookPgs ;$i++): ?>
			<img src="img/lookbook/<?= $i; ?>.jpg" alt="Nick and Campbell Lookbook Page <?= $i; ?>" />
			<?php endfor; ?>
			<div class="clearfix"></div>
		</div>	
	</div>
	<div id="campaign_controls">
	
		<div id="prev_arrow" class="co-arrow campaign-arrow left"></div>
		<h2 >Click arrows to browse.</h2>
		<div id="next_arrow" class="co-arrow campaign-arrow right"></div>
	</div>
	</section>
	
	
	<section id="s_contact">
		<div class="sidebar">
			<h1>Contact</h1>
		</div>
		<div class="section-content">
			<h2>Contact Us Today</h2>
			<h4>info@nickandcampbell.com</h4>	
			<h4>office.917.328.6408</h4>	
			<h4>inquiries welcome</h4>	
			<?= $this->contactForm; ?>
			<div class="clearfix"></div>
		</div>
	</section>
	
	
<!-- footer sections	-->
	<section id="s_shipping">
		<div class="sidebar">
			<h1>Shipping</h1>
		</div>
		<div class="section-content policies">
			<h2>Please review our shipping policy</h2>
			<p>We ship almost entirely via <a href="http://www.ups.com/" title="United Parcel Service">United Parcel Service</a> (UPS). For orders that weigh less than two pounds, you will find <a href="http://usps.com" title="United States Postal Service">United States Postal Service</a> (USPS) more economical.</p>
			<p>International orders are shipped primarily by USPS. International customers are encouraged to place and order. We will not charge your credit card until we send and you accept a shipping quote.</p>
			<p>Under normal circumstances, most orders ship out within 24-48 hours. However, due to large order volumes, weather conditions or circumstances beyond our control, we will ship your order out as soon as possible. We use recycled boxes and packing materials for mail orders.</p>
			<p>* To see your shipping charges in advance of placing an order, place the desired items into your shopping cart by clicking on the buy buttons. Then click on the small picture of the shopping cart in the upper right hand corner (located next to 'log In'). This will bring up a page that show you all the items in your cart. Enter your zip code in the box labeled 'Destination Zip Code'. You can try different shipping methods by clicking on the down arrow located next to 'Shipping'. Select a shipping method (e.g. USPS, UPS, Fed Ex, 3 day select etc...) and then click Recalculate. This will show you shipping charges before placing your order or entering any personal information.</p>
			<h2>Shipping Times</h2>
			<p>Most orders are shipped within 24-48 hours. Do not count the day the order was shipped. Fed Ex Home Delivery delivers on Saturday at no extra charge but does not deliver on Monday. Small orders that weigh less than two pounds are best shipped via USPS Priority Mail</p>
			<div class="clearfix"></div>
		</div>
	</section>
	<section id="s_returns">
		<div class="sidebar">
			<h1>Returns</h1>
		</div>
		<div class="section-content policies">
			<h2>Please review our returns policy</h2>
			<p>Our current return policy is very basic because we are only selling underwear online at this time. Your purchase may be returned only if you have received the wrong size or style of underwear from your online order. We will insure your order will be replaced with the right size or style of underwear originally ordered online.</p>
			<p>Thank you.</p>
			<p>Sincerely,</p>
			<p>Nick + Campbell</p>
			<p>The Team</p>
			<div class="clearfix"></div>
		</div>
	</section>
	<section id="s_sitemap">
		<div class="sidebar">
			<h1>Sitemap</h1>
		</div>
		<div class="section-content policies">
			<h2>Can't Find what you're looking for? Ask us a question <a href="contact" rel="address:/contact" title="Ask a question">here</a>.</h2>
			<ul>
				<li><a href="/" title="">Home</a></li>
				<li><a href="learn" title="">Learn</a></li>
				<li><a href="shop" title="">Shop</a></li>
				<li><a href="campaign" title="">Campaign</a></li>
				<li><a href="contact" title="">Contact</a></li>
				<li><a href="shipping" title="">Shipping Policy</a></li>
				<li><a href="returns" title="">Returns Policy</a></li>
				<li><a href="http://www.facebook.com/nickandcampbell" title="">Nick + Campbell Facebook Page</a></li>
				<li><a href="#" title="">Nick + Campbell On Twitter</a></li>
				<li><a href="#" title="">Nick + Campbell Google+ Page</a></li>
				<li><a href="#" title="">Login</a></li>
			</ul>

			<div class="clearfix"></div>
		</div>
	</section>
	<div id='overlay'></div>
</div>