<ul class="shop-subnav subnav-grad">
	<li><a href="shop" rel="address:/shop" title="Back">« Back</a></li>
</ul>
<div class="product-content">
	<h1><?= $this->product->name; ?></h1>
	<img src="img/shop/mens/underwear/large/product-1.jpg" alt=""/>
	<?= $this->form; ?>
	<div id="add_to_cart_form_extended">
		<label>Price:</label><p>$<?= $this->product->price; ?></p>
		<div class="checkout-btn btn">Checkout</div>
	</div>
</div>