<?= $this->doctype() ?>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title>Admin :: Nick + Campbell :: <?= APPLICATION_ENV; ?></title>
	<meta name="description" content="Nick and Campbell is a Designer Mens Fashion Line">
	<meta name="author" content="Owen Corso">
	<meta name="keywords" content="underwear, nick lemons, fashion, mens, womens, clothing, apparel">
	<meta name="viewport" content="width=device-width,initial-scale=1">

	 <?php echo $this->headLink(); ?>

	<script src="/js/libs/modernizr-2.0.6.min.js"></script>
	<!--[if gte IE 9]>
  		<style type="text/css">.gradient {filter: none;}</style>
	<![endif]-->
</head>
<body>
<div id="container">
	<header>
		<div id="auth">
			<ul>
				<li><?= $this->loggedInAs(); ?></li>
				<li>|</li>
				<li><?= $this->dashboardOrRegister(); ?></li>
			</ul>
		</div>
		
		<aside id="logo">
			<a id="logo_off" href="<?= $this->baseUrl(); ?>/" title="Nick + Campbell"><img src="/img/logo/nc-logo-off.png"/></a>
			<a id="logo_on" style="display:none" href="<?= $this->baseUrl(); ?>/" title="Nick + Campbell"><img src="/img/logo/nc-logo-on.png"/></a>
		</aside>
		<nav class="shadow"><div class="nav-edge"></div>
			<ul class="headings">
				<li><a id='l-1' href="<?= $this->baseUrl(); ?>/learn" title="Learn about Nick and Campbell">Learn</a></li>
				<li><a id='l-2'	href="<?= $this->baseUrl(); ?>/shop" title="Shop Nick and Campbell Mens Underwear">Shop</a></li>
				<li><a id='l-3' href="<?= $this->baseUrl(); ?>/campaign" title="The Nick and Campbell Fashion Campaign">Campaign</a></li>
				<li><a id='l-4' href="<?= $this->baseUrl(); ?>/contact" title="Contact Nick and Campbell">Contact</a></li>
			</ul>
		</nav>
		<div class="clearfix"></div>
	</header>
<?php echo $this->layout()->content; ?>
	<footer>
		<a id="sm-1" class="social-media" target="_blank" href="http://twitter.com/nickandcampbell" title="Follow Nick and Campbell on Twitter">Follow Us on Twitter</a>
		<a id="sm-2" class="social-media" target="_blank" href="http://www.facebook.com/nickandcampbell" title="Like Nick and Campbell on Facebook">Like Us on Facebook</a>
		<a id="sm-3" class="social-media" target="_blank" href="https://plus.google.com/112776621395476756717" title="+1 Nick and Campbell on Google+">+1 Nick and Campbell on Google+</a>
		<g:plusone></g:plusone>
		<aside><ul>
			<li>&copy; nick+campbell 2011</li>
			<li><img src="/img/icons/list-style-img.png" alt="Nick and Campbell List Separator" /></li>
			<li><a href="<?= $this->baseUrl(); ?>/shipping" title="Shipping Policy">Shipping Policy</a></li>
			<li><img src="/img/icons/list-style-img.png" alt="Nick and Campbell List Separator" /></li>
			<li><a href="<?= $this->baseUrl(); ?>/returns" title="Returns Policy">Returns Policy</a></li>
			<li><img src="/img/icons/list-style-img.png" alt="Nick and Campbell List Separator" /></li>
			<li><a href="<?= $this->baseUrl(); ?>/sitemap" title="Sitemap">Sitemap</a></li>
		</ul></aside>
	</footer>
</div> <!--! end of #container -->
<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>-->
<script>window.jQuery || document.write('<script src="/js/libs/jquery-1.7.1.min.js"><\/script>')</script>
<script src="/js/libs/jquery.address-1.4.min.js"></script>
<?= $this->headScript(); ?>
<script src="/js/site/docReady.js" type="text/javascript" ></script>
<!-- end scripts-->

<script>
/*	var _gaq=[['_setAccount','UA-19135050-5'],['_trackPageview']];
	(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
	g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
	s.parentNode.insertBefore(g,s)}(document,'script'));
*/
</script>

<!--[if lt IE 7 ]>
	<script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
	<script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
<![endif]-->

</body>
</html>
