<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title>Nick + Campbell | Mens Underwear | NYC :: <?= APPLICATION_ENV; ?></title>
	<meta name="description" content="">
	<meta name="author" content="Owen Corso">

	<meta name="viewport" content="width=device-width,initial-scale=1">
	 <?php echo $this->headLink()->appendStylesheet('css/style.css') ?>

	<script src="js/libs/modernizr-2.0.6.min.js"></script>
</head>
<body>
<div id="container">
	<header>
		<aside id="logo">
			<a id="logo_off" href="/" title="Nick + Campbell"><img src="img/logo/nc-logo-off.png"/></a>
			<a id="logo_on" rel="address:/" style="display:none" href="/" title="Nick + Campbell"><img src="img/logo/nc-logo-on.png"/></a>
		</aside>
		<nav><img alt="Nick and Campbell Mens Underwear New York" src="img/nav/nav.png"/>
			<ul>
				<li><a id='l-1' rel="address:/learn" 	href="learn" title="Learn about Nick and Campbell">Learn</a></li>
				<li><a id='l-2' rel="address:/shop" 	href="shop" title="Shop Nick and Campbell Mens Underwear">Shop</a></li>
				<li><a id='l-3' rel="address:/campaign" href="campaign" title="The Nick and Campbell Fashion Campaign">Campaign</a></li>
				<li><a id='l-4' rel="address:/contact" 	href="contact" title="Contact Nick and Campbell">Contact</a></li>
			</ul>
		</nav>
		<div class="clearfix"></div>
	</header>
<?php echo $this->layout()->content; ?>
	<footer>
		<a class="social-media" href="http://twitter.com/nickandcampbell" title="Follow Nick and Campbell on Twitter"><img src="img/icons/icon-twitter.png" alt="Follow Nick and Campbell on Twitter"/>Follow Us on Twitter</a>
		<a class="social-media" href="http://www.facebook.com/nickandcampbell" title="Like Nick and Campbell on Facebook"><img src="img/icons/icon-facebook.png" alt="Fan Nick and Campbell on Facebook"/>Like Us on Facebook</a>
		<aside><ul>
			<li><a href="#" title="Shipping Policy">Shipping Policy</a></li>
			<li>|</li>
			<li><a href="#" title="Returns Policy">Returns Policy</a></li>
			<li>|</li>
			<li><a href="#" title="Sitemap">Sitemap</a></li>
		</ul></aside>
	</footer>
</div> <!--! end of #container -->
<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>-->
<script>window.jQuery || document.write('<script src="js/libs/jquery-1.6.2.min.js"><\/script>')</script>
	<script src="js/libs/jquery.address-1.4.min.js"></script>
	<script src="js/site/mainController.js"></script>
	<script src="js/site/shopController.js"></script>
	<script src="js/site/campaignController.js"></script>
<script src="js/libs/plugins.js"></script>
<script src="js/site/docReady.js"></script>
<!-- end scripts-->

<script>
/*	var _gaq=[['_setAccount','UA-19135050-5'],['_trackPageview']];
	(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
	g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
	s.parentNode.insertBefore(g,s)}(document,'script'));
*/
</script>

<!--[if lt IE 7 ]>
	<script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
	<script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
<![endif]-->

</body>
</html>
