<script type="text/javascript">
<!--
	var shippingArr = [];
	<?php foreach($this->shipping as $sh){
		echo "shippingArr.push($sh);\n";
	} ?>
//-->
</script>
<div id="s_checkout" class="section" role="main">
	<h1>Checkout</h1>
	<!-- <h3><? //echo $this->form->isValid($_POST) ? "You're Almost Done!" : "<span style='color: red;'>Please Fix Errors Below.</span>"; ?></h3> -->
	<h3><?= isset($this->isValid) || $this->isGet ? "You're Almost Done!" : "<span style='color: red;'>Please Fix Errors Below.</span>"; ?></h3>
	 <ul id="indicator_list" >
		<div id="co_indicator"></div>
		<li><h2>1.</h2><h4>Shipping</h4></li>
		<li><h2>2.</h2><h4>Billing</h4></li>
		<li><h2>3.</h2><h4>Confirm</h4></li>
	</ul>
	<div id="co_carousel">
		<div id="co_prev" class="co-arrow" title="Previous">Previous</div>
	<?php
		echo $this->form;
	?>
		<div id="co_next" class="co-arrow" title="Next">Next</div>
	<script type="text/javascript">document.getElementById("co_carousel").style.display = "none";</script>
	</div>
</div>