<div id="s_checkout" class="section" role="main">
	<h1>Checkout</h1>
	<h3>Your Almost Done!</h3>
	 <ul id="indicator_list" >
		<div id="co_indicator"></div>
		<li><h2>1.</h2><h4>Shipping</h4></li>
		<li><h2>2.</h2><h4>Billing</h4></li>
		<li><h2>3.</h2><h4>Confirm</h4></li>
	</ul>
	<div id="co_carousel">
		<div id="co_prev" class="co-arrow" title="Previous">Previous</div>
	<?php
		echo $this->form;
	?>
		<div id="co_next" class="co-arrow" title="Next">Next</div>
	
	</div>
</div>