<?php if (count($this->cartObj->items) == 0): ?>
<h2>Your shopping cart is empty.</h2>
<?php else : ?>
<ul>
<?php foreach($this->cartObj->items as $item): ?>
	<li class='item' data-Pid="<?= $item['pid']; ?>">
		<p><?= $item['name']; ?></p>
		<p><?= $item['size_name']; ?> <span class="quantity" >x<?= $item['quantity']; ?></span>
			<span class='remove-item'>remove</span>
			<span class='right'><?= $item['price']; ?></span>
		</p>
	</li>
<?php endforeach; ?>
	<li class="shipping-total" style="display: none;">shipping: <span id="shipping_cost" class="right">$0.00</span></li>
	<li class="tax" style="display:none;">tax: <span id="tax_cost" class="right">$0.00</span></li>
	<li class='subtotal'>subtotal: <span id="total_cost" class='right'>$<?= $this->cartObj->subTotal; ?></span></li>
</ul>
<?php endif; ?>
<script type="text/javascript">
	var cart = {};
	cart.origTotal = <?= $this->cartObj->subTotal; ?>;
</script>