<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Orders</a></li>
		<li><a href="#tabs-2">Products</a></li>
	</ul>
	
	<div id="tabs-1">
		<table id="orders_grid" cellpadding="0" cellspacing="0" border="0" class="display">
			<thead>
				<tr>
					
					<th width="5">Order Number</th>
					<th width="5">Total Price</th>
					<th width="25">Customer Name</th>
					<th width="10">Email</th>
					<th width="10">Phone</th>
					<th width="10">Status</th>
				</tr>
			</thead>
			<tbody>
				
			</tbody>
			<tfoot>
				<tr>
					<th>Order Number</th>
					<th>Total Price</th>
					<th>Customer Name</th>
					<th>Email</th>
					<th>Phone</th>
					<th>Status</th>
				</tr>
			</tfoot>
		</table>
	</div>
	<div id="tabs-2">
		<table id="products_grid" cellpadding="0" cellspacing="0" border="0" class="display" id="example2">
			<thead>
				<tr>
					<th>Product Id</th>
					<th>Style Id</th>
					<th>Name</th>
					<th>Description1</th>
					<th>Gender</th>
					<th>Category</th>
					<th>Price</th>
					<th>Campaign</th>
					<th>Label</th>
					<th>Size</th>
					<th>Color</th>
					<th>Weight</th>
					<th>SKU</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<th>Product Id</th>
					<th>Style Id</th>
					<th>Name</th>
					<th>Description1</th>
					<th>Gender</th>
					<th>Category</th>
					<th>Price</th>
					<th>Campaign</th>
					<th>Label</th>
					<th>Size</th>
					<th>Color</th>
					<th>Weight</th>
					<th>SKU</th>
				</tr>
			</tfoot>
			<tbody>
				
			</tbody>
		</table>
	</div>
</div>